### ISSUE TITLE
awesome!!! but seems to freeze obsidian for 20-30 seconds on paste?

### ISSUE THREAD

**Issue by zeltak** [ZackaryW/obsidian-image-inline#1]
Hi

first of all thank you is much for this..have been waiting forever for something like this (since I can't code myself.. :))

I installed and enabled the plugin but when I actually paste obsidian seems frozen for a good 20-30 seconds. is that normal or something on my machine?

thx so much again ,just made my day to discover this :D !!!

Z

**Comment by ZackaryW** [comment]
There are two likely scenarios:
1. image is too big, as of now, resizing of img is planned
2. most likely a machine issue, probably due to a weak encoding instruction set. 
3. we could also suspect a plugin collision
without enough information, I could only provide guesses
8k image clip and paste only causes 0.5 seconds freeze time on my two machines

**Comment by zeltak** [comment]
thx!

im on a m2 air with 24GB of memory so I suspect the image is to big? (what the recommended image size?)

also as a side note, I wonder if there is anything that can be done to still hide the full base64 link even in editing mode since it sometimes is a pain to scroll all the way down :) 

auto image resize sounds like a killer feature!

thanks so much again for putting the time into this!! its too awesome

Z

**Comment by ZackaryW** [comment]
i suspect this is a machine based problem

unfortunately, i dont own a mac, and im not sure if i could do much at my end.
i could try to add a new line after paste to avoid immediate expansion of links ( that could likely be the slowdown too due to visual rendering)

**Comment by sinkr** [comment]
FWIW, this plugin seemingly permanently freezes the iOS app with large images (i.e. those taken by the camera).

Small images work just fine (I tested a 34k PNG).
