### ISSUE TITLE
Feature request: drag existing image files in

### ISSUE THREAD

**Issue by ChrisBBBB** [ZackaryW/obsidian-image-inline#2]
First of all, thank you so much for this work; I've been looking for this and yet again, the community delivers. Thank you.

I'm sure you have lots of ideas for features; I'll log the request that this supports **existing** image files dragged in
And maybe even if there's an easy option of choosing if that file is store inline (as base64) or as an attachment in the normal way (maybe based upon the image size?) I'm guessing that most people would want larger images saved as files and small clip type images to go inline. At least that's how I'm planning to use it.

(or another idea - an option to convert a pasted inline image back out as a saved file attachment - if maybe you realise it's too big really)

Just ideas. Thank you again so much.
I have ver 0.3.0

**Comment by ZackaryW** [comment]
good idea, 👍 and yes reverting images are planned, but I have yet to layout the approach
