### ISSUE TITLE
Excel as image too ?!

### ISSUE THREAD

**Issue by ChrisBBBB** [ZackaryW/obsidian-image-inline#4]
I just discovered that when I have a bit of an Excel spreadsheet in the clipboard and paste it into Obsidian, it pastes in as an image.

I don't know if it's this plugin that's doing it or something else. If it's the plugin, that  wasn't what I was expecting at all, and maybe that could be a toggle in the setting. I've discovered another plug-in that allows Excel to be pasted in as markdown, but now I get the markdown table AND an image when I paste Excel.

 Sorry if this is nothing to do with the plugin, I just thought I'd mention it.

**Comment by ZackaryW** [comment]
Microsoft products these days seem to give all kinds of weird streams when working with it. Excel and onenote are known examples of copying images instead of actual tables while it is painful to go through options. 
Unfortunately, it is not related to this plugin and nothing I can do too
